// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: mm/v1/mm.proto

package mmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType message type enumeration
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED    MessageType = 0
	MessageType_MESSAGE_TYPE_REGISTER       MessageType = 1
	MessageType_MESSAGE_TYPE_REGISTER_ACK   MessageType = 2
	MessageType_MESSAGE_TYPE_DEPTH_SNAPSHOT MessageType = 3
	MessageType_MESSAGE_TYPE_QUOTE_REQUEST  MessageType = 4
	MessageType_MESSAGE_TYPE_QUOTE_RESPONSE MessageType = 5
	MessageType_MESSAGE_TYPE_QUOTE_REJECT   MessageType = 6
	MessageType_MESSAGE_TYPE_HEARTBEAT      MessageType = 7
	MessageType_MESSAGE_TYPE_ERROR          MessageType = 8
	MessageType_MESSAGE_TYPE_CONNECTION_ACK MessageType = 9 // Connection confirmation after token authentication
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_REGISTER",
		2: "MESSAGE_TYPE_REGISTER_ACK",
		3: "MESSAGE_TYPE_DEPTH_SNAPSHOT",
		4: "MESSAGE_TYPE_QUOTE_REQUEST",
		5: "MESSAGE_TYPE_QUOTE_RESPONSE",
		6: "MESSAGE_TYPE_QUOTE_REJECT",
		7: "MESSAGE_TYPE_HEARTBEAT",
		8: "MESSAGE_TYPE_ERROR",
		9: "MESSAGE_TYPE_CONNECTION_ACK",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":    0,
		"MESSAGE_TYPE_REGISTER":       1,
		"MESSAGE_TYPE_REGISTER_ACK":   2,
		"MESSAGE_TYPE_DEPTH_SNAPSHOT": 3,
		"MESSAGE_TYPE_QUOTE_REQUEST":  4,
		"MESSAGE_TYPE_QUOTE_RESPONSE": 5,
		"MESSAGE_TYPE_QUOTE_REJECT":   6,
		"MESSAGE_TYPE_HEARTBEAT":      7,
		"MESSAGE_TYPE_ERROR":          8,
		"MESSAGE_TYPE_CONNECTION_ACK": 9,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_mm_v1_mm_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_mm_v1_mm_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{0}
}

// QuoteStatus quote status
type QuoteStatus int32

const (
	QuoteStatus_QUOTE_STATUS_UNSPECIFIED QuoteStatus = 0
	QuoteStatus_QUOTE_STATUS_SUCCESS     QuoteStatus = 1
	QuoteStatus_QUOTE_STATUS_FAILED      QuoteStatus = 2
)

// Enum value maps for QuoteStatus.
var (
	QuoteStatus_name = map[int32]string{
		0: "QUOTE_STATUS_UNSPECIFIED",
		1: "QUOTE_STATUS_SUCCESS",
		2: "QUOTE_STATUS_FAILED",
	}
	QuoteStatus_value = map[string]int32{
		"QUOTE_STATUS_UNSPECIFIED": 0,
		"QUOTE_STATUS_SUCCESS":     1,
		"QUOTE_STATUS_FAILED":      2,
	}
)

func (x QuoteStatus) Enum() *QuoteStatus {
	p := new(QuoteStatus)
	*p = x
	return p
}

func (x QuoteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuoteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mm_v1_mm_proto_enumTypes[1].Descriptor()
}

func (QuoteStatus) Type() protoreflect.EnumType {
	return &file_mm_v1_mm_proto_enumTypes[1]
}

func (x QuoteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuoteStatus.Descriptor instead.
func (QuoteStatus) EnumDescriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{1}
}

// RejectReason rejection reason
type RejectReason int32

const (
	RejectReason_REJECT_REASON_UNSPECIFIED            RejectReason = 0
	RejectReason_REJECT_REASON_INSUFFICIENT_LIQUIDITY RejectReason = 1
	RejectReason_REJECT_REASON_PRICE_MOVED            RejectReason = 2
	RejectReason_REJECT_REASON_PAIR_NOT_SUPPORTED     RejectReason = 3
	RejectReason_REJECT_REASON_AMOUNT_TOO_SMALL       RejectReason = 4
	RejectReason_REJECT_REASON_AMOUNT_TOO_LARGE       RejectReason = 5
	RejectReason_REJECT_REASON_RATE_LIMITED           RejectReason = 6
	RejectReason_REJECT_REASON_INTERNAL_ERROR         RejectReason = 7
)

// Enum value maps for RejectReason.
var (
	RejectReason_name = map[int32]string{
		0: "REJECT_REASON_UNSPECIFIED",
		1: "REJECT_REASON_INSUFFICIENT_LIQUIDITY",
		2: "REJECT_REASON_PRICE_MOVED",
		3: "REJECT_REASON_PAIR_NOT_SUPPORTED",
		4: "REJECT_REASON_AMOUNT_TOO_SMALL",
		5: "REJECT_REASON_AMOUNT_TOO_LARGE",
		6: "REJECT_REASON_RATE_LIMITED",
		7: "REJECT_REASON_INTERNAL_ERROR",
	}
	RejectReason_value = map[string]int32{
		"REJECT_REASON_UNSPECIFIED":            0,
		"REJECT_REASON_INSUFFICIENT_LIQUIDITY": 1,
		"REJECT_REASON_PRICE_MOVED":            2,
		"REJECT_REASON_PAIR_NOT_SUPPORTED":     3,
		"REJECT_REASON_AMOUNT_TOO_SMALL":       4,
		"REJECT_REASON_AMOUNT_TOO_LARGE":       5,
		"REJECT_REASON_RATE_LIMITED":           6,
		"REJECT_REASON_INTERNAL_ERROR":         7,
	}
)

func (x RejectReason) Enum() *RejectReason {
	p := new(RejectReason)
	*p = x
	return p
}

func (x RejectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_mm_v1_mm_proto_enumTypes[2].Descriptor()
}

func (RejectReason) Type() protoreflect.EnumType {
	return &file_mm_v1_mm_proto_enumTypes[2]
}

func (x RejectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectReason.Descriptor instead.
func (RejectReason) EnumDescriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{2}
}

// ErrorCode error code
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED          ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_MESSAGE      ErrorCode = 1
	ErrorCode_ERROR_CODE_INVALID_SIGNATURE    ErrorCode = 2
	ErrorCode_ERROR_CODE_TIMEOUT              ErrorCode = 3
	ErrorCode_ERROR_CODE_INTERNAL             ErrorCode = 4
	ErrorCode_ERROR_CODE_NOT_REGISTERED       ErrorCode = 5
	ErrorCode_ERROR_CODE_DUPLICATE_REGISTER   ErrorCode = 6
	ErrorCode_ERROR_CODE_UNAUTHORIZED         ErrorCode = 7 // Token verification failed
	ErrorCode_ERROR_CODE_PAIR_NOT_WHITELISTED ErrorCode = 8 // Pair not whitelisted
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_MESSAGE",
		2: "ERROR_CODE_INVALID_SIGNATURE",
		3: "ERROR_CODE_TIMEOUT",
		4: "ERROR_CODE_INTERNAL",
		5: "ERROR_CODE_NOT_REGISTERED",
		6: "ERROR_CODE_DUPLICATE_REGISTER",
		7: "ERROR_CODE_UNAUTHORIZED",
		8: "ERROR_CODE_PAIR_NOT_WHITELISTED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":          0,
		"ERROR_CODE_INVALID_MESSAGE":      1,
		"ERROR_CODE_INVALID_SIGNATURE":    2,
		"ERROR_CODE_TIMEOUT":              3,
		"ERROR_CODE_INTERNAL":             4,
		"ERROR_CODE_NOT_REGISTERED":       5,
		"ERROR_CODE_DUPLICATE_REGISTER":   6,
		"ERROR_CODE_UNAUTHORIZED":         7,
		"ERROR_CODE_PAIR_NOT_WHITELISTED": 8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_mm_v1_mm_proto_enumTypes[3].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_mm_v1_mm_proto_enumTypes[3]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{3}
}

// Message is the unified wrapper for all WebSocket messages
type Message struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=mm.v1.MessageType" json:"type,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix milliseconds timestamp
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_DepthSnapshot
	//	*Message_QuoteRequest
	//	*Message_QuoteResponse
	//	*Message_QuoteReject
	//	*Message_Heartbeat
	//	*Message_Error
	//	*Message_ConnectionAck
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_mm_v1_mm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetDepthSnapshot() *DepthSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Message_DepthSnapshot); ok {
			return x.DepthSnapshot
		}
	}
	return nil
}

func (x *Message) GetQuoteRequest() *QuoteRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_QuoteRequest); ok {
			return x.QuoteRequest
		}
	}
	return nil
}

func (x *Message) GetQuoteResponse() *QuoteResponse {
	if x != nil {
		if x, ok := x.Payload.(*Message_QuoteResponse); ok {
			return x.QuoteResponse
		}
	}
	return nil
}

func (x *Message) GetQuoteReject() *QuoteReject {
	if x != nil {
		if x, ok := x.Payload.(*Message_QuoteReject); ok {
			return x.QuoteReject
		}
	}
	return nil
}

func (x *Message) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Message_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Message_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Message) GetConnectionAck() *ConnectionAck {
	if x != nil {
		if x, ok := x.Payload.(*Message_ConnectionAck); ok {
			return x.ConnectionAck
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_DepthSnapshot struct {
	DepthSnapshot *DepthSnapshot `protobuf:"bytes,3,opt,name=depth_snapshot,json=depthSnapshot,proto3,oneof"`
}

type Message_QuoteRequest struct {
	QuoteRequest *QuoteRequest `protobuf:"bytes,4,opt,name=quote_request,json=quoteRequest,proto3,oneof"`
}

type Message_QuoteResponse struct {
	QuoteResponse *QuoteResponse `protobuf:"bytes,5,opt,name=quote_response,json=quoteResponse,proto3,oneof"`
}

type Message_QuoteReject struct {
	QuoteReject *QuoteReject `protobuf:"bytes,6,opt,name=quote_reject,json=quoteReject,proto3,oneof"`
}

type Message_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,7,opt,name=heartbeat,proto3,oneof"`
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

type Message_ConnectionAck struct {
	ConnectionAck *ConnectionAck `protobuf:"bytes,9,opt,name=connection_ack,json=connectionAck,proto3,oneof"`
}

func (*Message_DepthSnapshot) isMessage_Payload() {}

func (*Message_QuoteRequest) isMessage_Payload() {}

func (*Message_QuoteResponse) isMessage_Payload() {}

func (*Message_QuoteReject) isMessage_Payload() {}

func (*Message_Heartbeat) isMessage_Payload() {}

func (*Message_Error) isMessage_Payload() {}

func (*Message_ConnectionAck) isMessage_Payload() {}

// ConnectionAck connection confirmation (sent after token authentication success)
type ConnectionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // Server time (Unix milliseconds)
	MmId          string                 `protobuf:"bytes,4,opt,name=mm_id,json=mmId,proto3" json:"mm_id,omitempty"`                    // Confirmed MM ID
	Config        *ConnectionConfig      `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionAck) Reset() {
	*x = ConnectionAck{}
	mi := &file_mm_v1_mm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionAck) ProtoMessage() {}

func (x *ConnectionAck) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionAck.ProtoReflect.Descriptor instead.
func (*ConnectionAck) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectionAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ConnectionAck) GetMmId() string {
	if x != nil {
		return x.MmId
	}
	return ""
}

func (x *ConnectionAck) GetConfig() *ConnectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConnectionAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ConnectionConfig connection configuration (sent by server)
type ConnectionConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DepthPushIntervalMs uint32                 `protobuf:"varint,1,opt,name=depth_push_interval_ms,json=depthPushIntervalMs,proto3" json:"depth_push_interval_ms,omitempty"` // Suggested push interval (milliseconds)
	QuoteTimeoutMs      uint32                 `protobuf:"varint,2,opt,name=quote_timeout_ms,json=quoteTimeoutMs,proto3" json:"quote_timeout_ms,omitempty"`                  // Quote timeout (milliseconds)
	HeartbeatIntervalMs uint32                 `protobuf:"varint,3,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`   // Heartbeat interval (milliseconds)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConnectionConfig) Reset() {
	*x = ConnectionConfig{}
	mi := &file_mm_v1_mm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionConfig) ProtoMessage() {}

func (x *ConnectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionConfig.ProtoReflect.Descriptor instead.
func (*ConnectionConfig) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectionConfig) GetDepthPushIntervalMs() uint32 {
	if x != nil {
		return x.DepthPushIntervalMs
	}
	return 0
}

func (x *ConnectionConfig) GetQuoteTimeoutMs() uint32 {
	if x != nil {
		return x.QuoteTimeoutMs
	}
	return 0
}

func (x *ConnectionConfig) GetHeartbeatIntervalMs() uint32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

// DepthSnapshot depth snapshot (pushed independently for each pool)
type DepthSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	PairId        string                 `protobuf:"bytes,2,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	MmId          string                 `protobuf:"bytes,3,opt,name=mm_id,json=mmId,proto3" json:"mm_id,omitempty"`
	TokenA        string                 `protobuf:"bytes,4,opt,name=token_a,json=tokenA,proto3" json:"token_a,omitempty"`
	TokenB        string                 `protobuf:"bytes,5,opt,name=token_b,json=tokenB,proto3" json:"token_b,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,6,rep,name=bids,proto3" json:"bids,omitempty"` // Bids (price descending)
	Asks          []*PriceLevel          `protobuf:"bytes,7,rep,name=asks,proto3" json:"asks,omitempty"` // Asks (price ascending)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthSnapshot) Reset() {
	*x = DepthSnapshot{}
	mi := &file_mm_v1_mm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthSnapshot) ProtoMessage() {}

func (x *DepthSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthSnapshot.ProtoReflect.Descriptor instead.
func (*DepthSnapshot) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{3}
}

func (x *DepthSnapshot) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *DepthSnapshot) GetPairId() string {
	if x != nil {
		return x.PairId
	}
	return ""
}

func (x *DepthSnapshot) GetMmId() string {
	if x != nil {
		return x.MmId
	}
	return ""
}

func (x *DepthSnapshot) GetTokenA() string {
	if x != nil {
		return x.TokenA
	}
	return ""
}

func (x *DepthSnapshot) GetTokenB() string {
	if x != nil {
		return x.TokenB
	}
	return ""
}

func (x *DepthSnapshot) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *DepthSnapshot) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// PriceLevel price level
type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`   // Price (tokenB/tokenA)
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // Amount (tokenA)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_mm_v1_mm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{4}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// QuoteRequest quote request
type QuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"` // Quote request unique ID (UUID)
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MmId          string                 `protobuf:"bytes,3,opt,name=mm_id,json=mmId,proto3" json:"mm_id,omitempty"`
	TokenIn       string                 `protobuf:"bytes,4,opt,name=token_in,json=tokenIn,proto3" json:"token_in,omitempty"`               // Input token address
	TokenOut      string                 `protobuf:"bytes,5,opt,name=token_out,json=tokenOut,proto3" json:"token_out,omitempty"`            // Output token address
	AmountIn      string                 `protobuf:"bytes,6,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`            // Input amount (uint256 string, 18 decimals)
	Recipient     string                 `protobuf:"bytes,7,opt,name=recipient,proto3" json:"recipient,omitempty"`                          // User recipient address
	Nonce         string                 `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`                                  // Anti-replay nonce
	Deadline      int64                  `protobuf:"varint,9,opt,name=deadline,proto3" json:"deadline,omitempty"`                           // Expiration timestamp (Unix seconds)
	SlippageBps   uint32                 `protobuf:"varint,10,opt,name=slippage_bps,json=slippageBps,proto3" json:"slippage_bps,omitempty"` // Slippage tolerance (basis points)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_mm_v1_mm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{5}
}

func (x *QuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *QuoteRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *QuoteRequest) GetMmId() string {
	if x != nil {
		return x.MmId
	}
	return ""
}

func (x *QuoteRequest) GetTokenIn() string {
	if x != nil {
		return x.TokenIn
	}
	return ""
}

func (x *QuoteRequest) GetTokenOut() string {
	if x != nil {
		return x.TokenOut
	}
	return ""
}

func (x *QuoteRequest) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *QuoteRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *QuoteRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *QuoteRequest) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *QuoteRequest) GetSlippageBps() uint32 {
	if x != nil {
		return x.SlippageBps
	}
	return 0
}

// QuoteResponse quote response
type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MmId          string                 `protobuf:"bytes,3,opt,name=mm_id,json=mmId,proto3" json:"mm_id,omitempty"`
	Status        QuoteStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=mm.v1.QuoteStatus" json:"status,omitempty"`
	Quote         *QuoteInfo             `protobuf:"bytes,5,opt,name=quote,proto3" json:"quote,omitempty"`                              // Quote info (for display)
	Order         *SignedOrder           `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`                              // Signed order (for on-chain execution)
	ValidUntil    int64                  `protobuf:"varint,7,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"` // Quote validity period (Unix milliseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_mm_v1_mm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{6}
}

func (x *QuoteResponse) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *QuoteResponse) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *QuoteResponse) GetMmId() string {
	if x != nil {
		return x.MmId
	}
	return ""
}

func (x *QuoteResponse) GetStatus() QuoteStatus {
	if x != nil {
		return x.Status
	}
	return QuoteStatus_QUOTE_STATUS_UNSPECIFIED
}

func (x *QuoteResponse) GetQuote() *QuoteInfo {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *QuoteResponse) GetOrder() *SignedOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *QuoteResponse) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

// QuoteInfo quote information (for frontend display)
type QuoteInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TokenIn          string                 `protobuf:"bytes,1,opt,name=token_in,json=tokenIn,proto3" json:"token_in,omitempty"`
	TokenOut         string                 `protobuf:"bytes,2,opt,name=token_out,json=tokenOut,proto3" json:"token_out,omitempty"`
	AmountIn         string                 `protobuf:"bytes,3,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOut        string                 `protobuf:"bytes,4,opt,name=amount_out,json=amountOut,proto3" json:"amount_out,omitempty"`
	AmountOutMinimum string                 `protobuf:"bytes,5,opt,name=amount_out_minimum,json=amountOutMinimum,proto3" json:"amount_out_minimum,omitempty"`
	Price            string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`                                // Execution price
	PriceImpact      string                 `protobuf:"bytes,7,opt,name=price_impact,json=priceImpact,proto3" json:"price_impact,omitempty"` // Price impact percentage
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuoteInfo) Reset() {
	*x = QuoteInfo{}
	mi := &file_mm_v1_mm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteInfo) ProtoMessage() {}

func (x *QuoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteInfo.ProtoReflect.Descriptor instead.
func (*QuoteInfo) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{7}
}

func (x *QuoteInfo) GetTokenIn() string {
	if x != nil {
		return x.TokenIn
	}
	return ""
}

func (x *QuoteInfo) GetTokenOut() string {
	if x != nil {
		return x.TokenOut
	}
	return ""
}

func (x *QuoteInfo) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *QuoteInfo) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *QuoteInfo) GetAmountOutMinimum() string {
	if x != nil {
		return x.AmountOutMinimum
	}
	return ""
}

func (x *QuoteInfo) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *QuoteInfo) GetPriceImpact() string {
	if x != nil {
		return x.PriceImpact
	}
	return ""
}

// SignedOrder signed order (aligned with contract IQuote.MMQuote structure)
type SignedOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signer        string                 `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`                        // MM signer address
	Pool          string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`                            // DarkPool Pool contract address
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                          // Anti-replay nonce (uint256 string)
	AmountIn      string                 `protobuf:"bytes,4,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`    // Input amount (18 decimals)
	AmountOut     string                 `protobuf:"bytes,5,opt,name=amount_out,json=amountOut,proto3" json:"amount_out,omitempty"` // Minimum output amount (18 decimals)
	Deadline      int64                  `protobuf:"varint,6,opt,name=deadline,proto3" json:"deadline,omitempty"`                   // Expiration timestamp (Unix seconds)
	ExtraData     []byte                 `protobuf:"bytes,7,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"` // Optional opaque bytes (demo uses empty bytes)
	Signature     []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                  // EIP-712 signature (65 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedOrder) Reset() {
	*x = SignedOrder{}
	mi := &file_mm_v1_mm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedOrder) ProtoMessage() {}

func (x *SignedOrder) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedOrder.ProtoReflect.Descriptor instead.
func (*SignedOrder) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{8}
}

func (x *SignedOrder) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *SignedOrder) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *SignedOrder) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *SignedOrder) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *SignedOrder) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *SignedOrder) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *SignedOrder) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *SignedOrder) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// QuoteReject reject quote
type QuoteReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	MmId          string                 `protobuf:"bytes,3,opt,name=mm_id,json=mmId,proto3" json:"mm_id,omitempty"`
	Reason        RejectReason           `protobuf:"varint,4,opt,name=reason,proto3,enum=mm.v1.RejectReason" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteReject) Reset() {
	*x = QuoteReject{}
	mi := &file_mm_v1_mm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteReject) ProtoMessage() {}

func (x *QuoteReject) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteReject.ProtoReflect.Descriptor instead.
func (*QuoteReject) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{9}
}

func (x *QuoteReject) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *QuoteReject) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *QuoteReject) GetMmId() string {
	if x != nil {
		return x.MmId
	}
	return ""
}

func (x *QuoteReject) GetReason() RejectReason {
	if x != nil {
		return x.Reason
	}
	return RejectReason_REJECT_REASON_UNSPECIFIED
}

func (x *QuoteReject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat heartbeat message
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          bool                   `protobuf:"varint,1,opt,name=ping,proto3" json:"ping,omitempty"`
	Pong          bool                   `protobuf:"varint,2,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_mm_v1_mm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{10}
}

func (x *Heartbeat) GetPing() bool {
	if x != nil {
		return x.Ping
	}
	return false
}

func (x *Heartbeat) GetPong() bool {
	if x != nil {
		return x.Pong
	}
	return false
}

// Error error message
type Error struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=mm.v1.ErrorCode" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RelatedQuoteId string                 `protobuf:"bytes,3,opt,name=related_quote_id,json=relatedQuoteId,proto3" json:"related_quote_id,omitempty"` // Related quote ID (optional)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_mm_v1_mm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_mm_v1_mm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_mm_v1_mm_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRelatedQuoteId() string {
	if x != nil {
		return x.RelatedQuoteId
	}
	return ""
}

var File_mm_v1_mm_proto protoreflect.FileDescriptor

const file_mm_v1_mm_proto_rawDesc = "" +
	"\n" +
	"\x0emm/v1/mm.proto\x12\x05mm.v1\"\xe4\x03\n" +
	"\aMessage\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.mm.v1.MessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12=\n" +
	"\x0edepth_snapshot\x18\x03 \x01(\v2\x14.mm.v1.DepthSnapshotH\x00R\rdepthSnapshot\x12:\n" +
	"\rquote_request\x18\x04 \x01(\v2\x13.mm.v1.QuoteRequestH\x00R\fquoteRequest\x12=\n" +
	"\x0equote_response\x18\x05 \x01(\v2\x14.mm.v1.QuoteResponseH\x00R\rquoteResponse\x127\n" +
	"\fquote_reject\x18\x06 \x01(\v2\x12.mm.v1.QuoteRejectH\x00R\vquoteReject\x120\n" +
	"\theartbeat\x18\a \x01(\v2\x10.mm.v1.HeartbeatH\x00R\theartbeat\x12$\n" +
	"\x05error\x18\b \x01(\v2\f.mm.v1.ErrorH\x00R\x05error\x12=\n" +
	"\x0econnection_ack\x18\t \x01(\v2\x14.mm.v1.ConnectionAckH\x00R\rconnectionAckB\t\n" +
	"\apayload\"\xd4\x01\n" +
	"\rConnectionAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12\x13\n" +
	"\x05mm_id\x18\x04 \x01(\tR\x04mmId\x12/\n" +
	"\x06config\x18\x05 \x01(\v2\x17.mm.v1.ConnectionConfigR\x06config\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xa5\x01\n" +
	"\x10ConnectionConfig\x123\n" +
	"\x16depth_push_interval_ms\x18\x01 \x01(\rR\x13depthPushIntervalMs\x12(\n" +
	"\x10quote_timeout_ms\x18\x02 \x01(\rR\x0equoteTimeoutMs\x122\n" +
	"\x15heartbeat_interval_ms\x18\x03 \x01(\rR\x13heartbeatIntervalMs\"\xd8\x01\n" +
	"\rDepthSnapshot\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x17\n" +
	"\apair_id\x18\x02 \x01(\tR\x06pairId\x12\x13\n" +
	"\x05mm_id\x18\x03 \x01(\tR\x04mmId\x12\x17\n" +
	"\atoken_a\x18\x04 \x01(\tR\x06tokenA\x12\x17\n" +
	"\atoken_b\x18\x05 \x01(\tR\x06tokenB\x12%\n" +
	"\x04bids\x18\x06 \x03(\v2\x11.mm.v1.PriceLevelR\x04bids\x12%\n" +
	"\x04asks\x18\a \x03(\v2\x11.mm.v1.PriceLevelR\x04asks\":\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\xa1\x02\n" +
	"\fQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\x12\x13\n" +
	"\x05mm_id\x18\x03 \x01(\tR\x04mmId\x12\x19\n" +
	"\btoken_in\x18\x04 \x01(\tR\atokenIn\x12\x1b\n" +
	"\ttoken_out\x18\x05 \x01(\tR\btokenOut\x12\x1b\n" +
	"\tamount_in\x18\x06 \x01(\tR\bamountIn\x12\x1c\n" +
	"\trecipient\x18\a \x01(\tR\trecipient\x12\x14\n" +
	"\x05nonce\x18\b \x01(\tR\x05nonce\x12\x1a\n" +
	"\bdeadline\x18\t \x01(\x03R\bdeadline\x12!\n" +
	"\fslippage_bps\x18\n" +
	" \x01(\rR\vslippageBps\"\xf9\x01\n" +
	"\rQuoteResponse\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\x12\x13\n" +
	"\x05mm_id\x18\x03 \x01(\tR\x04mmId\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.mm.v1.QuoteStatusR\x06status\x12&\n" +
	"\x05quote\x18\x05 \x01(\v2\x10.mm.v1.QuoteInfoR\x05quote\x12(\n" +
	"\x05order\x18\x06 \x01(\v2\x12.mm.v1.SignedOrderR\x05order\x12\x1f\n" +
	"\vvalid_until\x18\a \x01(\x03R\n" +
	"validUntil\"\xe6\x01\n" +
	"\tQuoteInfo\x12\x19\n" +
	"\btoken_in\x18\x01 \x01(\tR\atokenIn\x12\x1b\n" +
	"\ttoken_out\x18\x02 \x01(\tR\btokenOut\x12\x1b\n" +
	"\tamount_in\x18\x03 \x01(\tR\bamountIn\x12\x1d\n" +
	"\n" +
	"amount_out\x18\x04 \x01(\tR\tamountOut\x12,\n" +
	"\x12amount_out_minimum\x18\x05 \x01(\tR\x10amountOutMinimum\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12!\n" +
	"\fprice_impact\x18\a \x01(\tR\vpriceImpact\"\xe4\x01\n" +
	"\vSignedOrder\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\tR\x06signer\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1b\n" +
	"\tamount_in\x18\x04 \x01(\tR\bamountIn\x12\x1d\n" +
	"\n" +
	"amount_out\x18\x05 \x01(\tR\tamountOut\x12\x1a\n" +
	"\bdeadline\x18\x06 \x01(\x03R\bdeadline\x12\x1d\n" +
	"\n" +
	"extra_data\x18\a \x01(\fR\textraData\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\x9f\x01\n" +
	"\vQuoteReject\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\x12\x13\n" +
	"\x05mm_id\x18\x03 \x01(\tR\x04mmId\x12+\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x13.mm.v1.RejectReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"3\n" +
	"\tHeartbeat\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\bR\x04ping\x12\x12\n" +
	"\x04pong\x18\x02 \x01(\bR\x04pong\"q\n" +
	"\x05Error\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.mm.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x10related_quote_id\x18\x03 \x01(\tR\x0erelatedQuoteId*\xbb\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MESSAGE_TYPE_REGISTER\x10\x01\x12\x1d\n" +
	"\x19MESSAGE_TYPE_REGISTER_ACK\x10\x02\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_DEPTH_SNAPSHOT\x10\x03\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_QUOTE_REQUEST\x10\x04\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_QUOTE_RESPONSE\x10\x05\x12\x1d\n" +
	"\x19MESSAGE_TYPE_QUOTE_REJECT\x10\x06\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\a\x12\x16\n" +
	"\x12MESSAGE_TYPE_ERROR\x10\b\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_CONNECTION_ACK\x10\t*^\n" +
	"\vQuoteStatus\x12\x1c\n" +
	"\x18QUOTE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14QUOTE_STATUS_SUCCESS\x10\x01\x12\x17\n" +
	"\x13QUOTE_STATUS_FAILED\x10\x02*\xa6\x02\n" +
	"\fRejectReason\x12\x1d\n" +
	"\x19REJECT_REASON_UNSPECIFIED\x10\x00\x12(\n" +
	"$REJECT_REASON_INSUFFICIENT_LIQUIDITY\x10\x01\x12\x1d\n" +
	"\x19REJECT_REASON_PRICE_MOVED\x10\x02\x12$\n" +
	" REJECT_REASON_PAIR_NOT_SUPPORTED\x10\x03\x12\"\n" +
	"\x1eREJECT_REASON_AMOUNT_TOO_SMALL\x10\x04\x12\"\n" +
	"\x1eREJECT_REASON_AMOUNT_TOO_LARGE\x10\x05\x12\x1e\n" +
	"\x1aREJECT_REASON_RATE_LIMITED\x10\x06\x12 \n" +
	"\x1cREJECT_REASON_INTERNAL_ERROR\x10\a*\x9e\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_MESSAGE\x10\x01\x12 \n" +
	"\x1cERROR_CODE_INVALID_SIGNATURE\x10\x02\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\x03\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x04\x12\x1d\n" +
	"\x19ERROR_CODE_NOT_REGISTERED\x10\x05\x12!\n" +
	"\x1dERROR_CODE_DUPLICATE_REGISTER\x10\x06\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\a\x12#\n" +
	"\x1fERROR_CODE_PAIR_NOT_WHITELISTED\x10\bB@Z>github.com/ThetaSpace/DarkPool-Market-Maker-Example/mm/v1;mmv1b\x06proto3"

var (
	file_mm_v1_mm_proto_rawDescOnce sync.Once
	file_mm_v1_mm_proto_rawDescData []byte
)

func file_mm_v1_mm_proto_rawDescGZIP() []byte {
	file_mm_v1_mm_proto_rawDescOnce.Do(func() {
		file_mm_v1_mm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mm_v1_mm_proto_rawDesc), len(file_mm_v1_mm_proto_rawDesc)))
	})
	return file_mm_v1_mm_proto_rawDescData
}

var file_mm_v1_mm_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_mm_v1_mm_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_mm_v1_mm_proto_goTypes = []any{
	(MessageType)(0),         // 0: mm.v1.MessageType
	(QuoteStatus)(0),         // 1: mm.v1.QuoteStatus
	(RejectReason)(0),        // 2: mm.v1.RejectReason
	(ErrorCode)(0),           // 3: mm.v1.ErrorCode
	(*Message)(nil),          // 4: mm.v1.Message
	(*ConnectionAck)(nil),    // 5: mm.v1.ConnectionAck
	(*ConnectionConfig)(nil), // 6: mm.v1.ConnectionConfig
	(*DepthSnapshot)(nil),    // 7: mm.v1.DepthSnapshot
	(*PriceLevel)(nil),       // 8: mm.v1.PriceLevel
	(*QuoteRequest)(nil),     // 9: mm.v1.QuoteRequest
	(*QuoteResponse)(nil),    // 10: mm.v1.QuoteResponse
	(*QuoteInfo)(nil),        // 11: mm.v1.QuoteInfo
	(*SignedOrder)(nil),      // 12: mm.v1.SignedOrder
	(*QuoteReject)(nil),      // 13: mm.v1.QuoteReject
	(*Heartbeat)(nil),        // 14: mm.v1.Heartbeat
	(*Error)(nil),            // 15: mm.v1.Error
}
var file_mm_v1_mm_proto_depIdxs = []int32{
	0,  // 0: mm.v1.Message.type:type_name -> mm.v1.MessageType
	7,  // 1: mm.v1.Message.depth_snapshot:type_name -> mm.v1.DepthSnapshot
	9,  // 2: mm.v1.Message.quote_request:type_name -> mm.v1.QuoteRequest
	10, // 3: mm.v1.Message.quote_response:type_name -> mm.v1.QuoteResponse
	13, // 4: mm.v1.Message.quote_reject:type_name -> mm.v1.QuoteReject
	14, // 5: mm.v1.Message.heartbeat:type_name -> mm.v1.Heartbeat
	15, // 6: mm.v1.Message.error:type_name -> mm.v1.Error
	5,  // 7: mm.v1.Message.connection_ack:type_name -> mm.v1.ConnectionAck
	6,  // 8: mm.v1.ConnectionAck.config:type_name -> mm.v1.ConnectionConfig
	8,  // 9: mm.v1.DepthSnapshot.bids:type_name -> mm.v1.PriceLevel
	8,  // 10: mm.v1.DepthSnapshot.asks:type_name -> mm.v1.PriceLevel
	1,  // 11: mm.v1.QuoteResponse.status:type_name -> mm.v1.QuoteStatus
	11, // 12: mm.v1.QuoteResponse.quote:type_name -> mm.v1.QuoteInfo
	12, // 13: mm.v1.QuoteResponse.order:type_name -> mm.v1.SignedOrder
	2,  // 14: mm.v1.QuoteReject.reason:type_name -> mm.v1.RejectReason
	3,  // 15: mm.v1.Error.code:type_name -> mm.v1.ErrorCode
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_mm_v1_mm_proto_init() }
func file_mm_v1_mm_proto_init() {
	if File_mm_v1_mm_proto != nil {
		return
	}
	file_mm_v1_mm_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_DepthSnapshot)(nil),
		(*Message_QuoteRequest)(nil),
		(*Message_QuoteResponse)(nil),
		(*Message_QuoteReject)(nil),
		(*Message_Heartbeat)(nil),
		(*Message_Error)(nil),
		(*Message_ConnectionAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mm_v1_mm_proto_rawDesc), len(file_mm_v1_mm_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mm_v1_mm_proto_goTypes,
		DependencyIndexes: file_mm_v1_mm_proto_depIdxs,
		EnumInfos:         file_mm_v1_mm_proto_enumTypes,
		MessageInfos:      file_mm_v1_mm_proto_msgTypes,
	}.Build()
	File_mm_v1_mm_proto = out.File
	file_mm_v1_mm_proto_goTypes = nil
	file_mm_v1_mm_proto_depIdxs = nil
}
